# Generated by Django 4.0.2 on 2022-02-05 14:40

import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Bookmark",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                ("object_id", models.CharField(max_length=250)),
            ],
            options={
                "verbose_name": "Bookmarked Object",
                "verbose_name_plural": "Bookmarked Objects",
                "db_table": "bookmark",
                "ordering": ["created"],
            },
        ),
        migrations.CreateModel(
            name="TagItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                ("name", models.SlugField(max_length=100)),
            ],
            options={
                "verbose_name": "Tag Item",
                "verbose_name_plural": "Tag Items",
                "db_table": "tag_item",
                "ordering": ["-created"],
            },
        ),
    ]
